<?php

/**
 * Mandatory file comment.
 */

/**
 * Simple class comment with many tags but we ignore them.
 *
 * @category   _wrong_category
 * @package    PHP_CodeSniffer
 * @package    ADDITIONAL PACKAGE TAG
 * @subpackage SUBPACKAGE TAG
 * @author     Original Author <author@example.com>
 * @author       Greg Sherwood gsherwood@squiz.net
 * @author     Mr T <t@squiz.net>
 * @author
 * @copyright  1997~1994 The PHP Group
 * @license    http://www.php.net/license/3_0.txt
 * @see
 * @see
 * @link       sdfsdf
 * @see        Net_Sample::Net_Sample()
 * @see        Net_Other
 * @deprecated asd
 * @unknown    Unknown tag
 * @since      Class available since Release 1.2.0
 */
class Checking_Tags
{

}//end class

/**
 * {@inheritdoc}
 */
class InheritDocClass implements SomeInterface
{

}
